mainConfiguration: https://gihub.com/module-federation/aegis
# tasks:
#   - name: build & watch
#     init: |
#       yarn
#       yarn build
#     command: |
#       gp async-done build
#       yarn watch

#   - name: start
#     command: |
#       gp async-await build
#       yarn start
